import os
import subprocess
import json

# Step 1: Set up configuration for weiboSpider in config.json
config_data = {
    "keyword_list": ["数字主权", "网络主权", "数据主权"]
    "since_date": "2024-01-01",  # Starting date for posts
    "end_date": "2024-12-31",  # Ending date for posts
    "output_format": ["csv"],  # Save output as CSV
    "output_dir": "./weibo_output"  # Directory to store the output
}

# Write the configuration to config.json
config_path = "./config.json"
with open(config_path, 'w', encoding='utf-8') as config_file:
    json.dump(config_data, config_file, ensure_ascii=False, indent=4)

print(f"Configuration saved to {config_path}")

# Step 2: Run weiboSpider using the generated config.json
try:
    # Run weiboSpider with the custom configuration
    subprocess.run(["python3", "-m", "weibo_spider", "--config_path", config_path], check=True)
    print("weiboSpider ran successfully.")

except subprocess.CalledProcessError as e:
    print(f"An error occurred while running weiboSpider: {e}")

# Step 3: Check for output
output_dir = config_data["output_dir"]

if os.path.exists(output_dir):
    print(f"Output saved in {output_dir}.")
else:
    print("No output found. Check configuration and try again.")
